import "server-only";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { products } from "@/db/schema";

export const MAX_IMAGE_SIZE = 900 * 1024;
export const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const BUCKET = "product-images";

function storageClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Product image storage is not configured.");
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  }).storage.from(BUCKET);
}

// Call only after seller authorization and resolving the shop from the database.
export async function uploadProductImage(image: File, shopId: number): Promise<string> {
  if (!Number.isSafeInteger(shopId) || shopId <= 0) throw new Error("Invalid shop.");
  if (!ALLOWED_IMAGE_TYPES.includes(image.type) || image.size <= 0 || image.size > MAX_IMAGE_SIZE) {
    throw new Error("Invalid product image.");
  }
  const extension = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp" }[image.type];
  const path = `products/${shopId}/${randomUUID()}.${extension}`;
  const storage = storageClient();
  const { error } = await storage.upload(path, Buffer.from(await image.arrayBuffer()), {
    contentType: image.type, cacheControl: "3600", upsert: false,
  });
  if (error) throw new Error("Product image upload failed. Please try again.");
  return storage.getPublicUrl(path).data.publicUrl;
}

export function ownedProductImagePath(imageUrl: string | null, shopId: number): string | null {
  if (!imageUrl || !Number.isSafeInteger(shopId) || shopId <= 0) return null;
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
  if (!base) return null;
  const prefix = `${base}/storage/v1/object/public/${BUCKET}/`;
  if (!imageUrl.startsWith(prefix)) return null;
  const path = imageUrl.slice(prefix.length);
  const pattern = new RegExp(`^products/${shopId}/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\.(jpg|png|webp)$`);
  return pattern.test(path) ? path : null;
}

// Input must be a URL read from the owned product row or generated by this module,
// never a submitted URL. Local/foreign/shared images are deliberately retained.
export async function removeUnusedProductImage(imageUrl: string | null, shopId: number): Promise<void> {
  const path = ownedProductImagePath(imageUrl, shopId);
  if (!path) return;
  try {
    const [reference] = await db.select({ id: products.id }).from(products)
      .where(eq(products.imageUrl, imageUrl!)).limit(1);
    if (reference) return;
    const { error } = await storageClient().remove([path]);
    if (error) console.warn("Product image cleanup deferred; an unreferenced object may remain.");
  } catch {
    // Retain the object when DB/Storage state is uncertain; never undo a saved product.
    console.warn("Product image cleanup deferred; an unreferenced object may remain.");
  }
}
